### ISSUE TITLE
💡 idea: Ollama support

### ISSUE THREAD

**Issue by Twilek-de** [mattermost/mattermost-plugin-ai#127]
Provide direct Ollama support for a quick and easy self hosted setup.

**Comment by crspeller** [comment]
@Twilek-de Just noted Ollama adding OpenAI compatibility: https://ollama.ai/blog/openai-compatibility
Does that work for you?

**Comment by Twilek-de** [comment]
Oh good catch. Just fired up Ollama with their latest docker container. OpenAI compatible endpoint works fine when evoking it with curl. With  Mattermost AI plugin nothing happens. There is no error message but the ollama container does not ramp up CPU time, as it does when it is running a query. Don´t know what is happing.

**Comment by Twilek-de** [comment]
Hmm Ollama supports a subset of the OpenAI API, namely completion. There is no support for streaming yet and I seem to remember that the MM AI Plugin uses the streaming endpoint....

**Comment by crspeller** [comment]
@Twilek-de It works for me if I set the API URL to `http://localhost:11434/v1` Maybe just add the `/v1`?
If that doesn't work for you please post the mattermost server logs and any logs from ollama.

**Comment by Twilek-de** [comment]
Yes! That was it. Works now for me too. Thanks!

**Comment by Twilek-de** [comment]
Hmm somehow the new version does not want to talk to ollama anymore…
{
  "caller": "app/plugin_api.go:1003",
  "error": "error, status code: 404, message: json: cannot unmarshal number into Go value of type openai.ErrorResponse",
  "level": "error",
  "msg": "Streaming result to post failed",
  "plugin_id": "mattermost-ai",
  "timestamp": "2024-03-11 21:13:08.070 Z"
}

**Comment by Twilek-de** [comment]
Found the "streamingTimeoutSeconds" setting. Is working again now.
