### ISSUE TITLE
Add regenerate button

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-ai#13]
It would be great if the user could press a regenerate button if they don't like the response. Especially for creative tasks this can be valuable.

It can look like this:
![image](https://github.com/mattermost/mattermost-plugin-ai/assets/3191642/644deaf2-611b-45a7-8a07-59e788f53603)

[Figma Link](https://www.figma.com/file/4Dq6Kl0kq8Zf186Ygf4NWT/AI-Explorations?type=design&node-id=66-153076&t=mxIQX6xYlJa94dZD-4)

**Comment by it33** [comment]
@ynott is this something you'd like to contribute?

**Comment by ynott** [comment]
@it33 
Thanks for the ping!

The implementation of the "regenerate" button is a very interesting story for me.
I'd like to try it, but I'm a bit busy with work and won't be able to help anytime soon.
Could you please get another person to do this?

**Comment by it33** [comment]
Sure thing, 

@crspeller I added a "Help Wanted" tag here, would that be okay? Should we add similar tags to other tickets? 

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/177788/a7f7254b-6122-4774-a6dd-13a26036c2e8)
