### ISSUE TITLE
🐛 bug: Not able to active in Mattermost V6&V7

### ISSUE THREAD

**Issue by akinlong** [mattermost/mattermost-plugin-ai#131]
## Description

I am using Matteromst V6 and trying to install the plugin, it was not able to active with below error message
![image](https://github.com/mattermost/mattermost-plugin-ai/assets/11705474/7b42ff43-c337-4698-8d8c-09376752e3a1)

I can't find any version limitation in this repository. Does that work as designed or it has a version limitation?

## Steps to reproduce

Upload plugin and active

**Comment by akinlong** [comment]
I upgraded to V7.1 and still not able to active:
![image](https://github.com/mattermost/mattermost-plugin-ai/assets/11705474/1813b9f8-fdaf-40c2-92a1-dbe2546dab14)

**Comment by crspeller** [comment]
@akinlong I have not done testing on older versions. I plan on bumping the min required version. V6 and V7 are both unsupported so no plans to support those. 
Are you in some way limited from using the latest release?

**Comment by akinlong** [comment]
> @akinlong I have not done testing on older versions. I plan on bumping the min required version. V6 and V7 are both unsupported so no plans to support those. Are you in some way limited from using the latest release?

I spent some time on that, it was caused by the robot name limitation, which requires more than 2(ai), so I downloaded the source and updated the robot name(aibot), it works on my 7.7 now.

I assume that is the reason why it doesn't work on 6, but I am not going to verify it recently.
