### ISSUE TITLE
Webapp capability: Textbox controls

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-ai#16]
Currently plugins do not have access to add buttons to the textbox.
For the plugin we would want the ability to add an AI button there and be able to manipulate the text within.

Should support something like this:
![image](https://github.com/mattermost/mattermost-plugin-ai/assets/3191642/5952c323-9025-421a-8cd7-864e9bc67d60)
[Figma Link](
https://www.figma.com/file/4Dq6Kl0kq8Zf186Ygf4NWT/AI-Explorations?type=design&node-id=4-74518&t=mxIQX6xYlJa94dZD-4)

**Comment by jespino** [comment]
This is already done and merged in master
