### ISSUE TITLE
💡 idea: Export Prometheus Metrics about usage

### ISSUE THREAD

**Issue by m00nyONE** [mattermost/mattermost-plugin-ai#173]
## Description

It would be very helpful to get some metrics about the usage.
Something like:
- total_requests
- tokens_sent
- tokens_received
- bytes_sent
- bytes_recieved

This would be amazing because it would allow for setting prometheus alerts. This can prevent cost explosion

**Comment by titanventura** [comment]
@jespino , i'd like to work on this if it is not actively being worked upon ! Could you please assign it to me ?

**Comment by crspeller** [comment]
Fixed by https://github.com/mattermost/mattermost-plugin-ai/pull/198 and https://github.com/mattermost/mattermost-plugin-ai/pull/202

**Comment by crspeller** [comment]
@titanventura Sorry @jespino already completed this one.
