### ISSUE TITLE
🐛 bug: I can't add a single LLM on the free Edition

### ISSUE THREAD

**Issue by fariazz** [mattermost/mattermost-plugin-ai#214]
## Description

It is my understanding that the free edition allows a single LLM, but in our case, we are not able to add a single one. You can see in the screenshot below that the submission button in the form to add an LLM is grayed out with the "enterprise" label. So we cannot add any single LLM into it:

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/1313597/285c1d50-7500-4fc8-96e4-fb601ebc320f)

The plugin is properly enabled:

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/1313597/5eb33c64-0d10-445d-a62b-ddfef40f8161)

## Steps to reproduce

**Environment info** (note it says "Enterprise Edition" but that's strange as we are not yet paid customers. I just installed the free version following the "omnibus setup" from the docs:

Mattermost Enterprise Edition
Modern communication from behind your firewall.

Mattermost Version: 9.9.0
Database Schema Version: 121
Build Number: 9307585135
Database: postgres

STEPS:

1) Install plugin
2) Go to the system console -> Plugins -> AI Copilot

EXPECTED: to be able to enter at least 1 LLM

OBSERVED: can't enter a single LLM as per the screenshot provided earlier.

**Comment by azigler** [comment]
Hey @fariazz thanks for checking out the plugin!

I can understand your confusion, but the fields _above_ where you indicated ("Name" through "Token Limit") are actually the fields for that 1 allotted LLM. That button you're pointing out allows a licensed Enterprise user to add multiple sets of those fields, thus configuring multiple LLMs.

If you [fill out those fields](https://docs.mattermost.com/configure/enable-copilot.html#enable) and save the settings (button at the bottom of the page) then your AI bot should work. Let us know if you have any more trouble.

Also, re: "Enterprise Edition" labeling, that refers to the base binary of the product you are using. It's considered E0, which means the Enterprise binary without a license (Free tier). I will pass along this feedback, however. Thanks again!

**Comment by matthewbirtch** [comment]
Thanks @azigler for answering this. I see the confusion and we can improve this. We will review this and come up with something that can clarify this.

**Comment by fariazz** [comment]
Thank you @azigler for the quick response! I can see how I misinterpreted the form - subform's submission hierarchy. That worked like a charm.

Also appreciate your clarification about the enterprise binary. Thanks again.
