### ISSUE TITLE
💡 idea: Suggestion to add system prompt setting 

### ISSUE THREAD

**Issue by hkjang** [mattermost/mattermost-plugin-ai#238]
## Description

Many models have problems handling Korean responses, possibly due to system prompts. It would be nice if system prompts as well as custom prompts could be changed. thank you

**Comment by andrewmurraydavid** [comment]
System prompts would be amazing! Our team is using the AI Copilot only for a specific thing and we have to use a prompt every time a new thread is created.

**Comment by crspeller** [comment]
@hkjang @andrewmurraydavid 

If you upgrade to the latest version of the plugin there should be a "Custom instructions" field in the system console per bot created. 

![image](https://github.com/user-attachments/assets/a0d165f2-ec72-4c7f-9c48-a80dd6e91c96)

Text in that field is included in the system prompt along side the regular system prompt the plugin uses. Does that fulfill your use cases or are you looking for something more specific?

**Comment by andrewmurraydavid** [comment]
Is self-hosted community edition stuck on 0.6.2? I don't see any updates available.

**Comment by crspeller** [comment]
@andrewmurraydavid You can upgrade manually by downloading from the releases page: https://github.com/mattermost/mattermost-plugin-ai/releases/tag/v1.0.0

The in product marketplace only gets updates now when the server version is upgraded.

**Comment by crspeller** [comment]
Going to close this as I think this concern is solved by the custom instructions. Feel free to reopen if the concern is not addressed.
