### ISSUE TITLE
💡 idea: Support for reading attached files

### ISSUE THREAD

**Issue by AnnoyingTechnology** [mattermost/mattermost-plugin-ai#245]
## Description

It would be nice if the attached files to a message/prompt could be read by the model. 

Currently, only images seem to be exposed to the model/API.

**Comment by se4n01** [comment]
I'm surprised this isn't done by default, chatgpt spews nonsense if you upload a file currently so I think this is a bug as well as a FR.

```
Se4n01
[8:23 AM]

can you transcribe the text in this text file?
test.txtTXT26B
Chat GPT
BOT
[8:23 AM]

I'm sorry, but I am unable to transcribe the text from an image file at the moment. If you can provide the text directly or in a different format, I'd be happy to help with the transcription.
```

**Comment by AnnoyingTechnology** [comment]
@azigler
