### ISSUE TITLE
🐛 bug: When using local LLM from Ollama the answers are distorted

### ISSUE THREAD

**Issue by artur-maj** [mattermost/mattermost-plugin-ai#260]
## Description

When using plugin with an LLM model running on Ollama server hosted locally (e.g., on another server within the same local network), the plugin successfully connects to the Ollama API and submits the prompts to the model. However, except very simple answers, almost all the answers received from the model are distorted and partially unreadable.

![image](https://github.com/user-attachments/assets/f129636c-4483-4904-8b68-c4c1571f4a52)

The distorted and unreadable answers could be due to incorrect rendering of Markdown tags within the model's responses or issues with handling the streaming of answer chunks.

Since other client software interacts with the same model without problems, the issue is almost certainly specific to the plugin itself. Here, for instance, comes the answer to the same prompt on the OpenWebUI interface:

![image](https://github.com/user-attachments/assets/f16e0374-a3a5-4a0d-a2c4-066c0349c85d)

or, using Ollama command line interface:

![image](https://github.com/user-attachments/assets/4e939c2a-7cad-4248-aff1-8d70f9f2067c)

## Steps to reproduce

1. Run Ollama on any server within the same network.
2. Run Gemma2 model, eg. Gemma2:27b or smaller.
3. Configure Copilot plugin within the Mattermost console:

![image](https://github.com/user-attachments/assets/44cc6d45-523c-4560-8250-11f1757cd155)

4. Use the chatbot to enter prompts and observe the answers.

**Comment by crspeller** [comment]
Hi @artur-maj Not seeing the same issue when I try it:
![image](https://github.com/user-attachments/assets/a0c2dd8c-f1ec-4558-8901-4d29d3ca1d36)

Can you provide more details on how your your setup?
Could you also provide the exact text of a response? (you can click copy text in the ... menu)
Does it happen consistently or only for some responses?

**Comment by artur-maj** [comment]
Yes the bot returns distorted messages all the time. I am not sure what else I can provide regarding the setup, other than I pasted above - it is a really, really simple setup based on Ollama defaults. Regarding the Ollama itself, it runs a 'vanilla' Gemma2:27b LLM instance with no fine-tuning, RAG or agent of any kind applied. In the above setup the Copilot plugin connects directly to the Ollama (no proxies between hosts). 
- ollama version: 0.3.3
- mattermost server version: 10.0.0
- copilot plugin version: 1.0.0

The prompt I just run:
```
Give me the basic rules of English language
```

And response (CTR+C > CTRL+V) from mattermost Web client (Safari web browser):
```
## The Basics Rules of the English Language: (Simplified)


While there are many rules & nuances to  English, here's a basic overview starting point


**Understanding Sentences:**

* **Subject** tells who or what the sentence isabout. (I saw.)

* **Verb** represents actions like "did", conditions( *"to seem", "is), *or states  (* "was"*).    (* I saw *( verb
)* **Object (optional)**  gets influenced by verbs.* ( " I ate*" a apple*)*".

**Word Order:** Think of most English sentence structure being this way; although flexibility  happens as the language matures

"[Subject] + [Verb]" and optionally adding the rest



I hope this short overview
 is helpful art!


.
```

![image](https://github.com/user-attachments/assets/2678f8e3-03ce-47f5-bded-628a297b3471)


On the MacOS desktop client the answer is distorted as well:
```
Hello Artur,

Navigating English Grammar Can Be Fun! 🇬🗳 Here are some basic but powerful rules:

**1. Subject-Verb Agreement: **Make sure your verbs match their subjects in number (singular or plural).  
*  One *cat* chases** two *mice**. (Singular / Pluran)

   A lot of mistakes for English language, the grammar is wrong


You said  * "A *dog* likes *bones*” 


I know that can **"appear correct**' to someone who just thinks it.

**

*"Many students do work together*"** I changed somethning which was grammaticakly incorrect:



***“Many _dogs_[subject]** *"__bark__,* [verb]**” is the same type of sentence construction.**





*"Does she run."* This question will ask and give a proper grammatical statement in reply



Let me know if

 You 

have 

 any 

more question! 🙂"  We all


make mistakes - Just trying to help
```

![image](https://github.com/user-attachments/assets/d3f95559-fa45-4df0-ace0-57771c219fe8)

As you can see the answer is very distorted - only certain parts of language are displayed, and the LLM's answer does not make sense. At the same time, when giving the same prompt on Ollama command line, everything works as it should. The answer is similar to the one you have provided.

**Comment by artur-maj** [comment]
@crspeller I can also see that in the example you pasted, the LLM response is a regular message, while in the case of my instance of LLM it is a reply to the message thread (vertical line on the left). Why is it so? Is it configurable somewhere?

**Comment by artur-maj** [comment]
UPDATE: I just upgraded Ollama to 0.4.7, and it seems that everything is working properly, now. Therefore the issue is with older versions of Ollama, for sure 0.3.3 and perhaps other versions, but older than 0.4.7.
