### ISSUE TITLE
Support previewing jupyter notebooks within MM.

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-ai#28]
It would be great if MM could support preview for jupyter notebooks in file uploads. Maybe use somthing like `nbconvert` to display?

**Comment by jespino** [comment]
I can take care of this using `notebook.js` that is javascript library that allows to preview ipynb files. Let me give it a try.

**Comment by crspeller** [comment]
This is harder to make secure then it seems. Probably suitable for a separate plugin.
