### ISSUE TITLE
Feature Idea: Auto-suggest emoji prefix for channel name

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-plugin-ai#31]
## Summary

Auto-suggest emoji for pre-fix of channel name 

## How important this is to me and why

Importance: Medium

Use cases:
1. Replace manual process of asking bot for a suggested emoji for naming a channel
2. Straight forward, value-add demo we can do we open source LLMs that doesn't require latest AI models

## Additional context/similar features

Any examples of good implementations of this capability.

**Comment by jespino** [comment]
@it33 can you give me more info of how do you invision this happening? I'm not sure how would be the user interface of this, or the system behavior. What triggers the prefix in the channels?

**Comment by crspeller** [comment]
This is not high impact for now.
