### ISSUE TITLE
Feature Idea: Ability to process a channel as if it were a thread

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-plugin-ai#32]
## Summary

We can run the AI bot on threads, but not channels and a lot of the data that's useful is across multiple posts in a channel. 

In initial implementation we could do some hard limit, like last XX posts, and whether or not to include threads or just first post. 

## How important this is to me and why

Importance: Medium

Use cases:

1. Ask bot in news feed channel to summarize all the mentions on `mattermost` in the past week or month 
2. Ask bot for summary of PRs cross-posted to channel, with ability to interrogate summaries, e.g. who made the most PRs? break out PRs by category, etc. 

## Additional context/similar features

Any examples of good implementations of this capability.

**Comment by crspeller** [comment]
Initial implementation is https://github.com/mattermost/mattermost-plugin-ai/pull/38
Going to close this as done for now. The future of this is likely lookup capabilities and general questions.
