### ISSUE TITLE
Feature Idea: Have thumbs up/down change color and visual after being toggled 

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-plugin-ai#33]
## Summary

Expected: After clicking thumbs up/down on evaluating an AI bot response, there's a visual indicator representing the change. 
Observed: No indication of button being pressed. 

## How important this is to me and why

Importance: Low

This is kind of a nice-to-have, but also a nice starter ticket for contributors to add. 

Use cases:
1. Toggling thumbs up/down in feedback on AI bot response

## Additional context/similar features

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/177788/e8feeb00-6669-455e-81ff-e5207f9e0e48)

Any examples of good implementations of this capability.

- Pretty standard

**Comment by it33** [comment]
@crspeller could you mention Matt Birch in this ticket to see about getting some assets for the toggle of the icons? 

Color change is okay, but we should ideally have something to support color blind use case--maybe just filled in rather than outline. 

I'd propose keeping this ticket open for community/contributors.

**Comment by it33** [comment]
@azigler or @crspeller can someone give me permissions so I can update the label on this ticket as "Up for grabs" or another label that could increase chances of someone external contributing?

**Comment by azigler** [comment]
@it33 I don't have edit access to this repository. @jwilander can you help us out?

**Comment by jwilander** [comment]
@it33 you should have invite for access now

**Comment by crspeller** [comment]
These are removed for 1.0
