### ISSUE TITLE
Feature Idea: Enable AI to process data in link previews

### ISSUE THREAD

**Issue by it33** [mattermost/mattermost-plugin-ai#43]
## Summary

In a channel with bot posts about articles from our user forum, end users can read link previews, however bot can't see the preview text, and can't process them in responses. The bot should be able to see them. 

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/177788/66dee7a1-30c1-4e5b-98f0-d541ea7caa81)

## How important this is to me and why

Without this ability, bot can't summarize contents from link preview posts users can read

Importance: Medium

Use cases:
1. Summarize channel including links 
2.
3.

## Additional context/similar features

Any examples of good implementations of this capability.

There are some alternate solutions to consider: 

a) Have a function that ingests the full article into the post, whether visibility or invisibly // there are some security risks with this 
b) Function could pull the link content at the time it's making the query,// potentially slow, brittle, and have security issues

**Comment by crspeller** [comment]
Too many security implications for now. Will revisit when we do more external data access.
