### ISSUE TITLE
Add ability to go back to a thread from the plugin RHS

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-ai#73]
We want to be able to go back to a previously open thread from the plugin RHS. This is currently not possible as the back button system only supports things like search and pinned posts.

RHS code: https://github.com/mattermost/mattermost/blob/86689b7ee69b6f914f7ceacd29b2f356a6b1888c/webapp/channels/src/components/rhs_header_post/rhs_header_post.tsx#L49

[Where it's used in figma designs](https://www.figma.com/file/4Dq6Kl0kq8Zf186Ygf4NWT/AI-Plugin?type=design&node-id=406-256799&mode=design&t=IL2R6Xi8vyNY72cc-4)

**Comment by crspeller** [comment]
That works as well. If the implementation is not clean we should probably fix the system. Otherwise if its simple then we can just do that direct plugin implementation.

**Comment by jespino** [comment]
I think the implementation is clean enough to do it in that way, and it looks like a preliminary step to get the whole RHS working as we want as part of the AI plugin. But I think we are going to face other kind of challenges there first. So I think this should be keep on hold. We can make it work, so no action is needed here for now. Whenever we start figuring out the whole RHS probably we have a better understanding of how deep we need to go with the extensibility in mattermost.

**Comment by crspeller** [comment]
Dropping this for now.
