### ISSUE TITLE
Feature Idea: Allow image input

### ISSUE THREAD

**Issue by EternalDeiwos** [mattermost/mattermost-plugin-ai#77]
## Summary

Support supplying uploaded images to models that support it (e.g. GPT-4) 

## How important this is to me and why

Importance: Medium

When used, diagrams tend to hold a lot of context in a particular discussion/thread. It might make summaries better if the diagrams/images were included in the context instead of being ignored.

Use cases:

1. Direct summary of any image (e.g. to create image captions)
2. Enhance existing ability to summarize content where there may be images inline

## Additional context/similar features

I'm not aware of any but GPT-4 is capable of accepting input from images.

**Comment by crspeller** [comment]
Certainly something we will want to add when it's available. Right now it's not available with the API: https://help.openai.com/en/articles/7127995-how-can-i-use-gpt-4-with-images

**Comment by EternalDeiwos** [comment]
My bad. I was sure I read somewhere that this was possible in GPT-4 already.

**Comment by NicksonYap** [comment]
I have opened a new issue to use the new `gpt-4-vision-preview` 
https://github.com/mattermost/mattermost-plugin-ai/issues/84
