### ISSUE TITLE
Feature Idea: Add in a "copy to clipboard" function onto AI messages

### ISSUE THREAD

**Issue by a3957273** [mattermost/mattermost-plugin-ai#91]
## Summary

Users has requested that a simple "Copy to clipboard" function for the AI response is added.  Clicking the button would copy the response from the AI to clipboard. An expansion to this _might_ also include separate copy buttons for each code snippet, etc.

## How important this is to me and why

Importance: Low

Use cases:
1.  A user wishes to transfer data from the AI to other systems.

## Additional context/similar features

The ChatGPT interface provides this.

**Comment by a3957273** [comment]
We would be happy to submit a pull request for this feature, if it's useful?

**Comment by crspeller** [comment]
There is already a copy text function built into the post menu. There are already copy buttons on code blocks as well. Is there a use case where that does not suffice? 

![image](https://github.com/mattermost/mattermost-plugin-ai/assets/3191642/ecace87d-b01b-4de3-927f-af86d92a6929)

**Comment by a3957273** [comment]
Ah, our bad.  Didn't think to check core Mattermost features!
